name: gh-pages publisher 🚀

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.5
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.8.5"
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: "x64"
      # You can test your matrix by printing the current Python version
      - name: Install pipx
        run: python3 -m pip install --user pipx==0.16.0.0
      - name: pipx ensurepath
        run: /home/runner/.local/bin/pipx ensurepath
      - name: pipX PATH
        run: PATH=/home/runner/.local/bin:$PATH
      - name: Install poetry
        run: pipx install poetry==1.1.0
      - name: pipx ensurepath
        run: /home/runner/.local/bin/pipx ensurepath
      - name: Test environment
        run: python3 --version ; pip --version ; pipx --version ; /home/runner/.poetry/bin/poetry --version
      - name: Build website
        run: make github_docs
